### ISSUE TITLE
CLI commands not working on the new update

### ISSUE THREAD

**Issue by Cyrus254** [giantas/sorter#1]
The app is really awsome and rocking, but the command line utility isn't that pretty. I am unable to execute any command whatsoever....i will be grateful if fixed.  The software really sorts my data since i am a shady person.
Thanks in advance

**Comment by giantas** [comment]
Thank you for the note. Apparently, the CLI commands do not work if you have the GUI installed through the Windows installer. Will fix this in the next update. For now, try install Python 3.4 (and above) on your pc then use the CLI provided by a clone of this repo. Try using the CLI commands provided in the README file.

**Comment by giantas** [comment]
GUI is now fully supported. No need for terminal support.

**Comment by giantas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove CLI](https://trello.com/c/sNyKI8A0/19-remove-cli)
